spring:
  datasource:
    url: jdbc:sqlite:authz.db
    driver-class-name: org.sqlite.JDBC

  sql:
    init:
      mode: always

jwt:
  jwks-uri: https://inspired-mole-13.clerk.accounts.dev/.well-known/jwks.json
  issuer: https://inspired-mole-13.clerk.accounts.dev
  audience:   # keep empty for now
  algorithm: RS256

cache:
  permissions:
    max-size: 1000
    expire-after-write-minutes: 5

logging:
  level:
    root: INFO
    com.venkatasai.auth.authz_service: DEBUG


